# nginx proxy address - http://172.17.0.1:80

name: dashy
x-logging: &default-logging
  options:
    max-size: '5m'
    max-file: '1'
  driver: json-file

services:
  app:
    image: lissy93/dashy:latest
    container_name: dashy-app
    hostname: ${BASE_HOST_NAME:-$HOSTNAME}
    restart: always
    pull_policy: always
    logging: *default-logging
    environment:
      TZ: ${TZ:-America/New_York}
    ports:
      - '172.17.0.1:80:80'
    volumes:
      - './rootfs/data/dashy:/data'
    networks:
      - dashy

networks:
  dashy:
    name: dashy
    external: false
